package org.moddingx.libx.datagen.provider.model;

import com.mojang.math.Quadrant;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.MultiVariant;
import net.minecraft.client.data.models.ModelProvider;
import net.minecraft.client.data.models.blockstates.MultiVariantGenerator;
import net.minecraft.client.data.models.blockstates.PropertyDispatch;
import net.minecraft.client.renderer.block.model.VariantMutator;
import net.minecraft.client.data.models.model.ModelTemplate;
import net.minecraft.client.data.models.model.ModelTemplates;
import net.minecraft.client.data.models.model.TextureMapping;
import net.minecraft.client.data.models.model.TextureSlot;
import net.minecraft.core.Direction;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.PackType;
import net.minecraft.server.packs.resources.ResourceManager;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.LeavesBlock;
import net.minecraft.world.level.block.LiquidBlock;
import net.minecraft.world.level.block.RenderShape;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.neoforged.neoforge.client.RenderTypeGroup;
import net.neoforged.neoforge.client.model.generators.template.ExtendedModelTemplateBuilder;
import net.neoforged.neoforge.fluids.FluidType;
import net.neoforged.neoforge.registries.NeoForgeRegistries;
import org.moddingx.libx.datagen.DatagenContext;
import org.moddingx.libx.impl.base.decoration.blocks.*;
import org.moddingx.libx.mod.ModX;
import org.moddingx.libx.util.lazy.LazyValue;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.*;
import java.util.function.Supplier;
import java.util.stream.Stream;

/**
 * A base class for block state and model providers. An extending class should call the
 * {@link #manualState(Block)} and {@link #manualModel(Block)} methods in {@link #setup()}.
 */
public abstract class BlockStateProviderBase extends ModelProvider {

    public static final ResourceLocation LEAVES_PARENT = ResourceLocation.fromNamespaceAndPath("minecraft", "block/leaves");
    public static final ResourceLocation BUTTON_PARENT = ResourceLocation.fromNamespaceAndPath("minecraft", "block/button");
    public static final ResourceLocation PRESSED_BUTTON_PARENT = ResourceLocation.fromNamespaceAndPath("minecraft", "block/button_pressed");
    public static final ResourceLocation PRESSURE_PLATE_PARENT = ResourceLocation.fromNamespaceAndPath("minecraft", "block/pressure_plate_up");
    public static final ResourceLocation PRESSED_PRESSURE_PLATE_PARENT = ResourceLocation.fromNamespaceAndPath("minecraft", "block/pressure_plate_down");

    protected final ModX mod;
    private final ResourceManager clientResources;

    private final Set<Block> manualState = new HashSet<>();
    private final Set<Block> existingModel = new HashSet<>();
    private final Map<Block, ResourceLocation> customModel = new HashMap<>();

    @Nullable
    private ResourceLocation currentRenderTypes = null;
    @Nullable
    private BlockModelGenerators blockModels = null;

    public BlockStateProviderBase(DatagenContext ctx) {
        super(ctx.output(), ctx.mod().modid);
        this.mod = ctx.mod();
        this.clientResources = ctx.resourceManager(PackType.CLIENT_RESOURCES);
    }

    @Nonnull
    @Override
    public final String getName() {
        return this.mod.modid + " block states and models";
    }

    @Nonnull
    @Override
    protected final Stream<? extends Holder<Block>> getKnownBlocks() {
        return BuiltInRegistries.BLOCK.listElements()
                .filter(holder -> this.mod.modid.equals(holder.getKey().location().getNamespace()))
                .filter(holder -> !this.manualState.contains(holder.value()));
    }

    @Nonnull
    @Override
    protected final Stream<? extends Holder<Item>> getKnownItems() {
        return Stream.empty();
    }

    /**
     * The provider will not process this block.
     */
    protected void manualState(Block block) {
        this.manualState.add(block);
    }

    /**
     * The provider will add a block state for a custom manual model.
     */
    protected void manualModel(Block block) {
        this.existingModel.add(block);
    }

    /**
     * The provider will add a block state with the given model location.
     */
    protected void manualModel(Block block, ResourceLocation model) {
        this.customModel.put(block, model);
    }

    /**
     * Sets the default render type for model templates generated by this provider.
     */
    protected void setRenderType(@Nullable ResourceLocation renderTypes) {
        this.currentRenderTypes = renderTypes;
    }

    @Override
    protected final void registerModels(@Nonnull BlockModelGenerators blockModels, @Nonnull ItemModelGenerators itemModels) {
        this.blockModels = blockModels;
        this.setup();

        for (ResourceLocation id : BuiltInRegistries.BLOCK.keySet().stream().sorted().toList()) {
            Block block = BuiltInRegistries.BLOCK.getValue(id);
            if (this.mod.modid.equals(id.getNamespace()) && !this.manualState.contains(block)) {
                if (this.existingModel.contains(block)) {
                    this.defaultState(id, block, () -> blockModelId(id));
                } else if (this.customModel.containsKey(block)) {
                    this.defaultState(id, block, () -> this.customModel.get(block));
                } else {
                    LazyValue<ResourceLocation> model = new LazyValue<>(() -> this.defaultModel(id, block));
                    this.defaultState(id, block, model::get);
                }
            }
        }
    }

    protected abstract void setup();

    /**
     * Creates a block state for the given block using the given model.
     */
    protected void defaultState(ResourceLocation id, Block block, Supplier<ResourceLocation> model) {
        BlockModelGenerators generators = this.models();

        if (block instanceof DecoratedWoodBlock decorated) {
            ResourceLocation textureSide;
            ResourceLocation textureTop;
            if (decorated.log == null) {
                textureSide = textureId(id);
                textureTop = textureId(id, "top");
            } else if (decorated.parent.has(decorated.log)) {
                ResourceLocation logId = Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent.get(decorated.log)));
                textureSide = textureId(logId);
                textureTop = textureId(logId);
            } else {
                textureSide = textureId(id);
                textureTop = textureId(id);
            }
            ResourceLocation axisModel = this.createBlockModel(
                    blockModelId(id),
                    ModelTemplates.CUBE_COLUMN,
                    TextureMapping.column(textureSide, textureTop),
                    this.currentRenderTypes
            );
            generators.blockStateOutput.accept(BlockModelGenerators.createAxisAlignedPillarBlock(block, variant(axisModel)));
        } else if (block instanceof DecoratedSlabBlock decorated) {
            ResourceLocation texture = textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            TextureMapping mapping = new TextureMapping().put(TextureSlot.BOTTOM, texture).put(TextureSlot.TOP, texture).put(TextureSlot.SIDE, texture);
            ResourceLocation bottom = this.createBlockModel(blockModelId(id), ModelTemplates.SLAB_BOTTOM, mapping, this.currentRenderTypes);
            ResourceLocation top = this.createBlockModel(blockModelId(id, "_top"), ModelTemplates.SLAB_TOP, mapping, this.currentRenderTypes);
            ResourceLocation doubled = blockModelId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            generators.blockStateOutput.accept(BlockModelGenerators.createSlab(block, variant(bottom), variant(top), variant(doubled)));
        } else if (block instanceof DecoratedStairBlock decorated) {
            ResourceLocation texture = textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            TextureMapping mapping = new TextureMapping().put(TextureSlot.BOTTOM, texture).put(TextureSlot.TOP, texture).put(TextureSlot.SIDE, texture);
            ResourceLocation inner = this.createBlockModel(blockModelId(id, "_inner"), ModelTemplates.STAIRS_INNER, mapping, this.currentRenderTypes);
            ResourceLocation straight = this.createBlockModel(blockModelId(id), ModelTemplates.STAIRS_STRAIGHT, mapping, this.currentRenderTypes);
            ResourceLocation outer = this.createBlockModel(blockModelId(id, "_outer"), ModelTemplates.STAIRS_OUTER, mapping, this.currentRenderTypes);
            generators.blockStateOutput.accept(BlockModelGenerators.createStairs(block, variant(inner), variant(straight), variant(outer)));
        } else if (block instanceof DecoratedWallBlock decorated) {
            ResourceLocation texture = textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            this.wallBlock(block, texture);
        } else if (block instanceof DecoratedFenceBlock decorated) {
            ResourceLocation texture = textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            this.fenceBlock(block, texture);
        } else if (block instanceof DecoratedFenceGateBlock decorated) {
            ResourceLocation texture = textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            this.fenceGateBlock(block, texture);
        } else if (block instanceof DecoratedButton decorated) {
            this.buttonBlock(block, textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent))));
        } else if (block instanceof DecoratedPressurePlate decorated) {
            this.pressurePlateBlock(block, textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent))));
        } else if (block instanceof DecoratedDoorBlock) {
            this.doorBlockWithRenderType(block, textureId(id, "bottom"), textureId(id, "top"), RenderTypes.CUTOUT);
        } else if (block instanceof DecoratedTrapdoorBlock) {
            this.trapdoorBlockWithRenderType(block, textureId(id), true, RenderTypes.CUTOUT);
        } else if (block instanceof DecoratedSign.Standing decorated) {
            ResourceLocation particle = textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            ResourceLocation signModel = this.createBlockModel(blockModelId(id), ModelTemplates.PARTICLE_ONLY, TextureMapping.particle(particle), this.currentRenderTypes);
            generators.blockStateOutput.accept(BlockModelGenerators.createSimpleBlock(block, variant(signModel)));
        } else if (block instanceof DecoratedSign.Wall decorated) {
            ResourceLocation particle = textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            ResourceLocation signModel = this.createBlockModel(blockModelId(id), ModelTemplates.PARTICLE_ONLY, TextureMapping.particle(particle), this.currentRenderTypes);
            generators.blockStateOutput.accept(BlockModelGenerators.createSimpleBlock(block, variant(signModel)));
        } else if (block instanceof DecoratedHangingSign.Ceiling decorated) {
            ResourceLocation particle = textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            ResourceLocation signModel = this.createBlockModel(blockModelId(id), ModelTemplates.PARTICLE_ONLY, TextureMapping.particle(particle), this.currentRenderTypes);
            generators.blockStateOutput.accept(BlockModelGenerators.createSimpleBlock(block, variant(signModel)));
        } else if (block instanceof DecoratedHangingSign.Wall decorated) {
            ResourceLocation particle = textureId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(decorated.parent)));
            ResourceLocation signModel = this.createBlockModel(blockModelId(id), ModelTemplates.PARTICLE_ONLY, TextureMapping.particle(particle), this.currentRenderTypes);
            generators.blockStateOutput.accept(BlockModelGenerators.createSimpleBlock(block, variant(signModel)));
        } else if (block.getStateDefinition().getProperties().contains(BlockStateProperties.HORIZONTAL_FACING)) {
            generators.blockStateOutput.accept(
                    MultiVariantGenerator.dispatch(block, variant(model.get()))
                            .with(BlockModelGenerators.ROTATION_HORIZONTAL_FACING_ALT)
            );
        } else if (block.getStateDefinition().getProperties().contains(BlockStateProperties.FACING)) {
            generators.blockStateOutput.accept(
                    MultiVariantGenerator.dispatch(block, variant(model.get()))
                            .with(PropertyDispatch.modify(BlockStateProperties.FACING)
                                    .select(Direction.DOWN, rotation(180, 0))
                                    .select(Direction.UP, rotation(0, 0))
                                    .select(Direction.NORTH, rotation(90, 0))
                                    .select(Direction.SOUTH, rotation(90, 180))
                                    .select(Direction.WEST, rotation(90, 270))
                                    .select(Direction.EAST, rotation(90, 90))
                            )
            );
        } else {
            generators.blockStateOutput.accept(BlockModelGenerators.createSimpleBlock(block, variant(model.get())));
        }
    }

    /**
     * Creates a model for the given block.
     */
    protected ResourceLocation defaultModel(ResourceLocation id, Block block) {
        if (block.getStateDefinition().getPossibleStates().stream().allMatch(state -> state.getRenderShape() != RenderShape.MODEL)) {
            if (block instanceof LiquidBlock liquidBlock) {
                Optional<ResourceLocation> tex = Optional.ofNullable(this.fluidTextureId(liquidBlock.fluid.getSource().getFluidType()));
                TextureMapping mapping = tex.map(TextureMapping::particle).orElseGet(() -> TextureMapping.particle(textureId(id)));
                return this.createBlockModel(blockModelId(id), ModelTemplates.PARTICLE_ONLY, mapping, this.currentRenderTypes);
            }
            return this.createBlockModel(blockModelId(id), ModelTemplates.PARTICLE_ONLY, TextureMapping.particle(textureId(id)), this.currentRenderTypes);
        } else if (block instanceof LeavesBlock) {
            return this.createBlockModel(blockModelId(id), ModelTemplates.CUBE_ALL, TextureMapping.cube(textureId(id)), RenderTypes.CUTOUT_MIPPED);
        } else {
            return this.createBlockModel(blockModelId(id), ModelTemplates.CUBE_ALL, TextureMapping.cube(textureId(id)), this.currentRenderTypes);
        }
    }

    /**
     * Creates a block state and models for a button.
     */
    public void buttonBlock(Block block, ResourceLocation texture) {
        TextureMapping mapping = TextureMapping.singleSlot(TextureSlot.TEXTURE, texture);
        ResourceLocation model = this.createBlockModel(blockModelId(block), ModelTemplates.BUTTON, mapping, this.currentRenderTypes);
        ResourceLocation pressed = this.createBlockModel(blockModelId(block, "_pressed"), ModelTemplates.BUTTON_PRESSED, mapping, this.currentRenderTypes);
        this.models().blockStateOutput.accept(BlockModelGenerators.createButton(block, variant(model), variant(pressed)));
    }

    /**
     * Creates a block state and models for a pressure plate.
     */
    public void pressurePlateBlock(Block block, ResourceLocation texture) {
        TextureMapping mapping = TextureMapping.singleSlot(TextureSlot.TEXTURE, texture);
        ResourceLocation model = this.createBlockModel(blockModelId(block), ModelTemplates.PRESSURE_PLATE_UP, mapping, this.currentRenderTypes);
        ResourceLocation pressed = this.createBlockModel(blockModelId(block, "_down"), ModelTemplates.PRESSURE_PLATE_DOWN, mapping, this.currentRenderTypes);
        this.models().blockStateOutput.accept(BlockModelGenerators.createPressurePlate(block, variant(model), variant(pressed)));
    }

    public void wallBlock(Block block, ResourceLocation texture) {
        TextureMapping mapping = TextureMapping.singleSlot(TextureSlot.WALL, texture);
        ResourceLocation post = this.createBlockModel(blockModelId(block, "_post"), ModelTemplates.WALL_POST, mapping, this.currentRenderTypes);
        ResourceLocation low = this.createBlockModel(blockModelId(block, "_side"), ModelTemplates.WALL_LOW_SIDE, mapping, this.currentRenderTypes);
        ResourceLocation tall = this.createBlockModel(blockModelId(block, "_side_tall"), ModelTemplates.WALL_TALL_SIDE, mapping, this.currentRenderTypes);
        this.models().blockStateOutput.accept(BlockModelGenerators.createWall(block, variant(post), variant(low), variant(tall)));
    }

    public void fenceBlock(Block block, ResourceLocation texture) {
        TextureMapping mapping = TextureMapping.singleSlot(TextureSlot.TEXTURE, texture);
        ResourceLocation post = this.createBlockModel(blockModelId(block, "_post"), ModelTemplates.FENCE_POST, mapping, this.currentRenderTypes);
        ResourceLocation side = this.createBlockModel(blockModelId(block, "_side"), ModelTemplates.FENCE_SIDE, mapping, this.currentRenderTypes);
        this.models().blockStateOutput.accept(BlockModelGenerators.createFence(block, variant(post), variant(side)));
    }

    public void fenceGateBlock(Block block, ResourceLocation texture) {
        TextureMapping mapping = TextureMapping.singleSlot(TextureSlot.TEXTURE, texture);
        ResourceLocation open = this.createBlockModel(blockModelId(block, "_open"), ModelTemplates.FENCE_GATE_OPEN, mapping, this.currentRenderTypes);
        ResourceLocation closed = this.createBlockModel(blockModelId(block), ModelTemplates.FENCE_GATE_CLOSED, mapping, this.currentRenderTypes);
        ResourceLocation wallOpen = this.createBlockModel(blockModelId(block, "_wall_open"), ModelTemplates.FENCE_GATE_WALL_OPEN, mapping, this.currentRenderTypes);
        ResourceLocation wallClosed = this.createBlockModel(blockModelId(block, "_wall"), ModelTemplates.FENCE_GATE_WALL_CLOSED, mapping, this.currentRenderTypes);
        this.models().blockStateOutput.accept(BlockModelGenerators.createFenceGate(block, variant(open), variant(closed), variant(wallOpen), variant(wallClosed), true));
    }

    public void doorBlockWithRenderType(Block block, ResourceLocation bottom, ResourceLocation top, ResourceLocation renderType) {
        TextureMapping mapping = TextureMapping.door(top, bottom);
        ResourceLocation bl = this.createBlockModel(blockModelId(block, "_bottom_left"), ModelTemplates.DOOR_BOTTOM_LEFT, mapping, renderType);
        ResourceLocation blo = this.createBlockModel(blockModelId(block, "_bottom_left_open"), ModelTemplates.DOOR_BOTTOM_LEFT_OPEN, mapping, renderType);
        ResourceLocation br = this.createBlockModel(blockModelId(block, "_bottom_right"), ModelTemplates.DOOR_BOTTOM_RIGHT, mapping, renderType);
        ResourceLocation bro = this.createBlockModel(blockModelId(block, "_bottom_right_open"), ModelTemplates.DOOR_BOTTOM_RIGHT_OPEN, mapping, renderType);
        ResourceLocation tl = this.createBlockModel(blockModelId(block, "_top_left"), ModelTemplates.DOOR_TOP_LEFT, mapping, renderType);
        ResourceLocation tlo = this.createBlockModel(blockModelId(block, "_top_left_open"), ModelTemplates.DOOR_TOP_LEFT_OPEN, mapping, renderType);
        ResourceLocation tr = this.createBlockModel(blockModelId(block, "_top_right"), ModelTemplates.DOOR_TOP_RIGHT, mapping, renderType);
        ResourceLocation tro = this.createBlockModel(blockModelId(block, "_top_right_open"), ModelTemplates.DOOR_TOP_RIGHT_OPEN, mapping, renderType);
        this.models().blockStateOutput.accept(BlockModelGenerators.createDoor(block, variant(bl), variant(blo), variant(br), variant(bro), variant(tl), variant(tlo), variant(tr), variant(tro)));
    }

    public void trapdoorBlockWithRenderType(Block block, ResourceLocation texture, boolean orientable, ResourceLocation renderType) {
        TextureMapping mapping = TextureMapping.singleSlot(TextureSlot.TEXTURE, texture);
        ResourceLocation top;
        ResourceLocation bottom;
        ResourceLocation open;
        if (orientable) {
            top = this.createBlockModel(blockModelId(block, "_top"), ModelTemplates.ORIENTABLE_TRAPDOOR_TOP, mapping, renderType);
            bottom = this.createBlockModel(blockModelId(block, "_bottom"), ModelTemplates.ORIENTABLE_TRAPDOOR_BOTTOM, mapping, renderType);
            open = this.createBlockModel(blockModelId(block, "_open"), ModelTemplates.ORIENTABLE_TRAPDOOR_OPEN, mapping, renderType);
            this.models().blockStateOutput.accept(BlockModelGenerators.createOrientableTrapdoor(block, variant(top), variant(bottom), variant(open)));
        } else {
            top = this.createBlockModel(blockModelId(block, "_top"), ModelTemplates.TRAPDOOR_TOP, mapping, renderType);
            bottom = this.createBlockModel(blockModelId(block, "_bottom"), ModelTemplates.TRAPDOOR_BOTTOM, mapping, renderType);
            open = this.createBlockModel(blockModelId(block, "_open"), ModelTemplates.TRAPDOOR_OPEN, mapping, renderType);
            this.models().blockStateOutput.accept(BlockModelGenerators.createTrapdoor(block, variant(top), variant(bottom), variant(open)));
        }
    }

    private BlockModelGenerators models() {
        if (this.blockModels == null) throw new IllegalStateException("Not in registerModels call.");
        return this.blockModels;
    }

    protected ResourceLocation createBlockModel(ResourceLocation modelId, ModelTemplate template, TextureMapping mapping, @Nullable ResourceLocation renderType) {
        ModelTemplate usedTemplate = template;
        if (renderType != null) {
            ExtendedModelTemplateBuilder builder = template.extend();
            builder.renderType(renderType);
            usedTemplate = builder.build();
        }
        return usedTemplate.create(modelId, mapping, this.models().modelOutput);
    }

    private static MultiVariant variant(ResourceLocation model) {
        return BlockModelGenerators.plainVariant(model);
    }

    private static VariantMutator rotation(int xRot, int yRot) {
        Quadrant x = toRotation(xRot);
        Quadrant y = toRotation(yRot);
        return variant -> {
            if (x != Quadrant.R0) variant = variant.with(VariantMutator.X_ROT.withValue(x));
            if (y != Quadrant.R0) variant = variant.with(VariantMutator.Y_ROT.withValue(y));
            return variant;
        };
    }

    private static Quadrant toRotation(int rot) {
        return switch(Math.floorMod(rot, 360)) {
            case 0 -> Quadrant.R0;
            case 90 -> Quadrant.R90;
            case 180 -> Quadrant.R180;
            case 270 -> Quadrant.R270;
            default -> throw new IllegalArgumentException("Invalid rotation: " + rot);
        };
    }

    protected static ResourceLocation blockModelId(ResourceLocation blockId) {
        return ResourceLocation.fromNamespaceAndPath(blockId.getNamespace(), "block/" + blockId.getPath());
    }

    protected static ResourceLocation blockModelId(ResourceLocation blockId, String suffix) {
        return ResourceLocation.fromNamespaceAndPath(blockId.getNamespace(), "block/" + blockId.getPath() + suffix);
    }

    protected static ResourceLocation blockModelId(Block block) {
        return blockModelId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(block)));
    }

    protected static ResourceLocation blockModelId(Block block, String suffix) {
        return blockModelId(Objects.requireNonNull(BuiltInRegistries.BLOCK.getKey(block)), suffix);
    }

    protected static ResourceLocation textureId(ResourceLocation blockId) {
        return ResourceLocation.fromNamespaceAndPath(blockId.getNamespace(), "block/" + blockId.getPath());
    }

    protected static ResourceLocation textureId(ResourceLocation blockId, String suffix) {
        return ResourceLocation.fromNamespaceAndPath(blockId.getNamespace(), "block/" + blockId.getPath() + "_" + suffix);
    }

    /**
     * Retrieves the texture for a given {@link FluidType}.
     */
    @Nullable
    protected ResourceLocation fluidTextureId(FluidType fluidType) {
        ResourceLocation id = NeoForgeRegistries.FLUID_TYPES.getKey(fluidType);
        if (id == null) throw new IllegalStateException("fluid type not registered: " + fluidType);
        ResourceLocation texture = ResourceLocation.fromNamespaceAndPath(id.getNamespace(), "block/" + id.getPath());
        ResourceLocation textureFile = ResourceLocation.fromNamespaceAndPath(texture.getNamespace(), "textures/" + texture.getPath() + ".png");
        if (this.clientResources.getResource(textureFile).isEmpty()) {
            throw new IllegalStateException("Could not find a texture for fluid " + id + ". You can provide one at " + texture + " or override fluidTextureId.");
        }
        return texture;
    }

    /**
     * Provides keys for builtin {@link RenderTypeGroup render types} to use.
     */
    public static class RenderTypes {

        private RenderTypes() {

        }

        public static final ResourceLocation SOLID = ResourceLocation.fromNamespaceAndPath("minecraft", "solid");
        public static final ResourceLocation CUTOUT = ResourceLocation.fromNamespaceAndPath("minecraft", "cutout");
        public static final ResourceLocation CUTOUT_MIPPED = ResourceLocation.fromNamespaceAndPath("minecraft", "cutout_mipped");
        public static final ResourceLocation CUTOUT_MIPPED_ALL = ResourceLocation.fromNamespaceAndPath("minecraft", "cutout_mipped_all");
        public static final ResourceLocation TRANSLUCENT = ResourceLocation.fromNamespaceAndPath("minecraft", "translucent");
        public static final ResourceLocation TRIPWIRE = ResourceLocation.fromNamespaceAndPath("minecraft", "tripwire");
    }
}
