modLoader="javafml"
loaderVersion="[41,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/ModdingX/LibX/issues"

[[mods]]
modId="libx"
version="${file.jarVersion}"
displayName="LibX"
displayURL="https://www.curseforge.com/minecraft/mc-mods/libx"
updateJSONURL="https://assets.melanx.de/updates/libx.json"
authors="ModdingX"
description='''
A library mod for minecraft.
'''

[[dependencies.libx]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.63,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.libx]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
