modLoader="javafml"
loaderVersion="[32,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/LibX/issues"

[[mods]]
modId="libx"
version="${file.jarVersion}"
displayName="LibX"
displayURL="https://www.curseforge.com/minecraft/mc-mods/libx"
authors="noeppi_noeppi, MelanX"
description='''
A library mod for minecraft.
'''

[[dependencies.libx]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.libx]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"