modLoader="javafml"
loaderVersion="[39,)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/noeppi-noeppi/LibX/issues"

[[mods]]
modId="libx"
version="${file.jarVersion}"
displayName="LibX"
displayURL="https://www.curseforge.com/minecraft/mc-mods/libx"
updateJSONURL="https://assets.melanx.de/updates/libx.json"
authors="noeppi_noeppi, MelanX"
description='''
A library mod for minecraft.
'''

[[dependencies.libx]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.libx]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"