modLoader="javafml"
loaderVersion="[${fml},)"
license="APACHE-2.0"
issueTrackerURL="https://github.com/ModdingX/LibX/issues"

[[mods]]
modId="libx"
version="${version}"
displayName="LibX"
displayURL="https://www.curseforge.com/minecraft/mc-mods/libx"
updateJSONURL="https://assets.melanx.de/updates/libx.json"
authors="ModdingX"
description='''
A library mod for minecraft.
'''

[[dependencies.libx]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.libx]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"
