modLoader="javafml"
loaderVersion="[4,)"
license="APACHE-2.0"
issueTrackerURL="${mod.issue_url}"

[[mods]]
modId="${mod.modid}"
version="${mod.version}"
displayName="${mod.name}"
displayURL="${mod.source_url}"
updateJSONURL="https://assets.melanx.de/updates/libx.json"
authors="ModdingX"
description='''
A library mod for minecraft.
'''

[[dependencies.libx]]
    modId="neoforge"
    type="required"
    versionRange="[${mod.neoforge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.libx]]
    modId="minecraft"
    type="required"
    versionRange="[${mod.minecraft},)"
    ordering="NONE"
    side="BOTH"
