name: 'Deploy Javadoc 📖'
on:
  push:
    branches:
      - '1.21'

jobs:
  deploy:
    if: startsWith(github.repository, 'ModdingX/') # don't run this in forks
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout 🛎️'
        uses: 'actions/checkout@v3'
        with:
          persist-credentials: false
      - name: 'Install Java 🍵'
        uses: 'actions/setup-java@v4'
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: 'Install and Build 🔧'
        run: './gradlew javadoc'

      - name: 'Deploy 🚀'
        uses: 'JamesIves/github-pages-deploy-action@15de0f09300eea763baee31dff6c6184995c5f6a'
        with:
          branch: gh-pages
          folder: 'build/docs/javadoc'
          clean: true
          git-config-name: 'Github Actions'
          git-config-email: '<>'
