name: 'Test pull request 📋'
on:
  pull_request:
    branches:
      - '1.21'

jobs:
  test:
    if: startsWith(github.repository, 'ModdingX/') # don't run this in forks
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout 🛎️'
        uses: 'actions/checkout@v4'
        with:
          persist-credentials: false

      - name: 'Install Java 🍵'
        uses: 'actions/setup-java@v4'
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: 'Run tests 📋'
        run: './gradlew test'
